#!/bin/bash

DOTFILES="bash_profile bashrc bash_aliases emacs gitconfig Xdefaults Xresources"

for file in $DOTFILES
do
    echo "Creating symlink from ~/.$file to ~/dotfiles/$file"
    ln -i -s ~/dotfiles/$file ~/.$file

    echo "Creating symlink from ~/".$file"_remote to ~/dotfiles/$file"
    ln -i -s ~/dotfiles/$file ~/."$file"_remote
done

